// Generated by LiveScript 1.4.0
var path, rework, reworkUrl, through, urlConvert, cssUrlConvert;
path = require('path');
rework = require('rework');
reworkUrl = require('rework-plugin-url');
through = require('through');
urlConvert = function(file, options){
  var filePath, cssContent;
  filePath = path.basename(file);
  cssContent = file.contents.toString();
  return rework(cssContent).use(reworkUrl(function(url){
    if (!/^data:image/.test(url)) {
      return url;
    }
  }));
};
cssUrlConvert = function(options){
  options || (options = {});
  return through.obj(function(file, enc, cb){
    var cssContent;
    cssContent = urlConvert(file, options);
    file.contents = new Buffer(cssContent);
    this.push(file);
    return cb();
  });
};
module.exports = cssUrlConvert;